name: Workflow 1 - Dependent Jobs

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build step
        run: |
          echo "::notice::Build started"
          echo "Building..."
          sleep 3

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test step
        run: |
          echo "::notice::Testing started"
          echo "Running tests..."
          sleep 3

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy step
        run: |
          echo "::notice::Deploy started"
          echo "Deploying..."
          sleep 3
